In [14]:
import numpy as np
import matplotlib.pyplot as plt

In [15]:
x = np.random.multivariate_normal(
    mean = [0, 0],
    cov = np.eye(2),
    size = 20
)
x

array([[-0.71306203,  0.1454593 ],
       [ 0.62597945, -0.47569012],
       [-0.32101269,  0.08521581],
       [-1.13728941,  1.78074224],
       [ 1.52035857,  0.69852263],
       [-0.7391131 , -0.16499174],
       [ 1.37158617, -0.76677663],
       [-0.10781043, -0.05011483],
       [ 0.08825756, -2.03060537],
       [ 0.34213709, -0.38400288],
       [-2.43551503, -0.57807305],
       [-1.01642762,  2.82387523],
       [ 0.49717891, -0.19746108],
       [-1.23250138, -0.03832301],
       [-1.31996103,  0.3412919 ],
       [ 0.45672855,  1.73297158],
       [-0.89531037, -0.23446022],
       [ 0.36707008, -2.42958946],
       [-0.18901297,  0.2441042 ],
       [-0.14273631,  0.55485722]])

In [ ]:
theta = np.array([-1 , 1])

array([ 0.85852133, -1.10166957,  0.4062285 ,  2.91803166, -0.82183594,
        0.57412135, -2.1383628 ,  0.0576956 , -2.11886293, -0.72613997,
        1.85744197,  3.84030284, -0.69463999,  1.19417837,  1.66125293,
        1.27624303,  0.66085015, -2.79665955,  0.43311718,  0.69759354])

In [18]:
y = np.random.normal(
    loc = x @ theta.T,
    scale = 0.1,
    size = 20
)
y

array([ 0.70402847, -1.17972562,  0.30564956,  2.90262405, -0.85175285,
        0.59817844, -2.08377689,  0.16049061, -2.1299977 , -0.57796554,
        1.79362766,  3.67773514, -0.63905476,  1.21785392,  1.61134101,
        1.36543741,  0.62842563, -2.90616728,  0.41108528,  0.68644791])

In [22]:
theta = np.random.multivariate_normal(
    mean = [0, 0],
    cov = np.eye(2),
    size = 20
)
f = x.T @ theta
f

array([[-2.99431351, -5.43507078],
       [ 3.21151742, -2.29020128]])

SyntaxError: invalid character '🚀' (U+1F680) (2597579702.py, line 1)